In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [3]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>

In [4]:
vector.ndim

1

In [5]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [6]:
matrix.ndim

2

Creating a Tensor

In [7]:
tensor = tf.constant([
                       [[1,2,3],
                       [4,5,6]],
                      
                       [[7,8,9],
                       [10,11,12]],
                      
                       [[13,14,15],
                       [16,17,18]]
                      
                      ])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [8]:
tensor.ndim

3

In [9]:
c_tensor = tf.Variable([10,7])
uc_tensor = tf.constant([10,7])

print(c_tensor)
print(uc_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [10]:
c_tensor[0].assign(7)
c_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

Creating Random Tensors

In [11]:
random_tensor1 = tf.random.Generator.from_seed(42)
random_tensor1 = random_tensor1.normal(shape = [3,2])     

random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.normal(shape = [3,2])    

random_tensor1 , random_tensor2 , random_tensor1 == random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffling a Tensor

In [12]:
not_shuffled = tf.constant( [[10,7],
                             [5,2],
                             [3,4]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2],
       [ 3,  4]])>

In [13]:
tf.random.set_seed(42)   # will not shuffle 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  2],
       [ 3,  4],
       [10,  7]])>

Creating Tensors using Numpy

In [14]:
import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [15]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

Manipulation of Tensors

In [16]:
tensor = tf.constant([[10,7],
                     [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [17]:
add = tensor + 10
sub = tensor - 10
mul = tensor * 10

add , sub , mul

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 0, -3],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]])>)

In [18]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [19]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

Matrix Multiplication

In [20]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [21]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

Matrix Multiplication using Tensors

In [22]:
X = tf.constant([[10,7],
                 [2,6],
                 [3,8]])
X.shape

TensorShape([3, 2])

In [23]:
Y = tf.constant([[12,6],
                 [6,2],
                 [8,3]])
Y.shape

TensorShape([3, 2])

In [24]:
X.shape , tf.reshape(Y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [25]:
tf.matmul(X,tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[134, 116,  81],
       [ 36,  60,  30],
       [ 52,  82,  42]])>

In [26]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  6],
        [ 3,  8]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[12,  6],
        [ 6,  2],
        [ 8,  3]])>)

In [27]:
tf.tensordot(tf.reshape(X,shape = (2,3)),Y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[178,  80],
       [154,  66]])>

In [28]:
tf.tensordot(tf.transpose(X),Y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[156,  73],
       [184,  78]])>

Changing Datatypes of Tensors

In [29]:
A = tf.constant([10,7])
print(A.dtype)

<dtype: 'int32'>


In [30]:
B = tf.constant([10.4,7.6])
print(B.dtype)

<dtype: 'float32'>


In [31]:
A_c = tf.cast(A,dtype=tf.int16)
print(A_c.dtype)

<dtype: 'int16'>


Aggregration the tensors

In [32]:
T = tf.constant(np.random.randint(1,100,size = 50))
T

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([91,  4, 18, 28, 49, 41, 92, 84, 70, 42, 33, 20, 89, 19, 14, 81,  2,
       94, 43, 62, 79, 50, 90, 82, 52, 21, 41, 59, 14, 15, 78, 41, 75, 85,
       25, 84, 99, 81,  5, 27, 98, 96, 82, 22,  8, 65, 38, 32, 47, 10])>

In [33]:
T.ndim, T.shape, tf.size(T)

(1, TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [34]:
import math
tf.math.reduce_sum(T)

<tf.Tensor: shape=(), dtype=int32, numpy=2577>

In [35]:
min = tf.math.reduce_min(T)
max = tf.math.reduce_max(T)
mean = tf.math.reduce_mean(T)

In [36]:
min ,max , mean

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=99>,
 <tf.Tensor: shape=(), dtype=int32, numpy=51>)

One Hot Encoding Tensors

In [37]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

**Exercise:**

In [38]:
# Q.1

scalar = tf.constant(10)
print(scalar)

vector = tf.constant([10,7])
print(vector)

matrix = tf.constant([[10,7],
                      [5,8],
                      [4,9]])
print(matrix)

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([10  7], shape=(2,), dtype=int32)
tf.Tensor(
[[10  7]
 [ 5  8]
 [ 4  9]], shape=(3, 2), dtype=int32)


In [39]:
# Q.2

tf. rank(matrix), matrix.ndim , matrix.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=2>, 2, TensorShape([3, 2]))

In [43]:
# Q.3

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,500))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,500))

random_1, random_2

(<tf.Tensor: shape=(3, 500), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ...,  0.17139332,
         -0.21565591, -0.06827872],
        [ 0.30605847, -0.7204267 ,  0.0638603 , ..., -1.3613358 ,
         -0.4253645 ,  0.7900614 ],
        [ 1.332233  , -1.2405047 , -0.14593224, ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(3, 500), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ...,  0.17139332,
         -0.21565591, -0.06827872],
        [ 0.30605847, -0.7204267 ,  0.0638603 , ..., -1.3613358 ,
         -0.4253645 ,  0.7900614 ],
        [ 1.332233  , -1.2405047 , -0.14593224, ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>)

In [46]:
# Q.4

random_1.shape , random_2.shape
random_1*random_2

<tf.Tensor: shape=(3, 500), dtype=float32, numpy=
array([[0.57241374, 0.00469869, 0.00576844, ..., 0.02937567, 0.04650747,
        0.00466198],
       [0.09367178, 0.5190146 , 0.00407814, ..., 1.853235  , 0.18093495,
        0.62419707],
       [1.7748446 , 1.538852  , 0.02129622, ..., 0.03792573, 0.31991345,
        0.0340004 ]], dtype=float32)>

In [51]:
tf.reshape(random_2, shape=(500,3))

<tf.Tensor: shape=(500, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       ...,
       [ 0.83872926,  1.0428203 , -0.64588344],
       [ 0.0022835 ,  0.58560526,  0.6404485 ],
       [ 0.1947453 ,  0.5656089 ,  0.18439196]], dtype=float32)>

In [52]:
# Q.5

tf.tensordot(random_1,random_2,axes=1)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,500], In[1]: [3,500] [Op:MatMul] name: 